# version: 2
# jobs:
#   build:
#     machine:
#       python:
#         version: 3.5.2

#       dependencies:
#         override:
#           - pip install -r requirements.txt

#       test:
#         override:
#           - nosetests tests/math-test.py

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: pip3 install -r requirements.txt --compile --no-cache-dir
      - run: nosetests tests/*